name: Verification Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# docker run --rm -it -u "$(id -u):$(id -g)" -v "${PWD}:/xk6" grafana/xk6 build v0.43.1 \
#   --with github.com/mostafa/xk6-kafka@v0.17.0 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.22' # The Go version to download (if necessary) and use.
    
    - name: install xk6
      run: go install go.k6.io/xk6/cmd/xk6@latest

    - name: create k6 ececutable
      run: xk6 build --with github.com/LeonAdato/xk6-output-statsd

    - name: creats k6 ececutable
      run: ls -lah
      
    - name: build image      
      run: docker build -t k6-statsd .

